### ISSUE TITLE
Remote login doesn't work

### ISSUE THREAD

**Issue by fvdm** [dougwollison/domainer#2]
Hi, I'm running into a problem with a multisite WP and Remote Login enabled.

The idea is that a user only logs in once on one of the sites and then is automatically logged in to all the sites they have access to. The login to the targeted site works fine and I get the message that login to the other site was successful too. But when I go to that site I have to login again.

Do you have an idea what may be the problem?

I can provide you access if you wish to take a look.

The setup:
- Clean WP 5.2.3 multisite install
- Domainer is the only plugin
- For the test only two sites: wptest1.domain.tld (main) and wptest2.otherdomain.tld
- Each site has their own domain name and is correctly mapped in the plugin
- The header `X-Content-Type-Options "nosniff"` is disabled
- The debug/php logs and the browser console log don't report any errors.

**Comment by dougwollison** [comment]
I've been noticing this on a live site I manage in my spare time; I don't think I'll be able to thoroughly debug it though until sometime next month, though due to multiple looming deadlines at work.

**Comment by fvdm** [comment]
Okay, I'm not in a hurry. When I find something myself I will post it here.

**Comment by dougwollison** [comment]
Strange, I did some testing on the other site I have this running on and I'm not getting any issues (anymore anyway).

Now, the one caveat is that the site isn't running on Domainer anymore; WordPress multisite now lets you change the full URL/domain of a site in a network under the settings after it's created, which has kinda rendered the plugin moot. I move the remote login code to a separatate plugin though (https://github.com/dougwollison/multilogin) but haven't published it yet.

I'm not sure if other code in Domainer was screwing stuff up but it may have been; it might be worth adjusting the network so you don't need domainer and instead just use the separate multilogin plugin. That's all I can think of at the moment.

**Comment by fvdm** [comment]
Hi Doug, indeed domain mapping now works without the plugin. Thanks, I didn't know.

I just tested the Multilogin plugin and it works for some sites. Although not yet consistent it does give me hope. I'll test more thoroughly in a couple of days to see what the logs say.
