### ISSUE TITLE
domainer refuses to delete

### ISSUE THREAD

**Issue by Rik44444** [dougwollison/domainer#5]
Hi, great plugin, but we decided to no longer use different domains for our translated pages. Trying to delete Domainer now, but i get an error: "Deletion failed: There has been a critical error on your website.Learn more about debugging in WordPress."

Any suggestions for how to solve this?

**Comment by dougwollison** [comment]
Are you able to edit/delete files on the site over FTP? It'll be the quickest way to make sure it's removed properly.

If so, you can manually delete it by doing the following:

1. Find and edit `wp-config.php`; locate and delete the line `define( 'SUNRISE', true );`
2. Find and delete `wp-content/sunrise.php`
3. Find and delete `wp-content/plugins/domainer/`

Normally plugins only need step 3, but because of the extra mods you'll need steps 1 and 2.

**Comment by cornishpasty** [comment]
Hi Doug, I have the same issue, unable to delete Domainer (1.2.1) on WP 5.5.1

Regarding your previous instruction, 

1) There is no SUNRISE reference in wp-config.php
2) wp-content/sunrise.php There is no such file at this location, do you mean...
wp-content/plugins/domainer/sunrise.php
3) I would like to delete the directory, but am concerned that I could break something. 

Any advice would be welcome!

Paul

**Comment by dougwollison** [comment]
That's odd, if the SUNRISE definition and file aren't installed I'm not sure what the problem could be.

Are you able to view the error log? If you add`define( 'WP_DEBUG', true );` in `wp-config.php` (if it's already there but `false`, change it to `true`), it should print out the error that's causing the issue.

Given the existing issues trying to uninstall the plugin, I don't think it would break anything further to just delete the domainer folder.

**Comment by cornishpasty** [comment]
Thanks, here's the error log:

PHP Fatal error:  Uncaught Error: Call to undefined function Domainer\get_sites() in /home/abcdef/public_html/wp-content/plugins/domainer/uninstall.php:35
Stack trace:
#0 /home/abcdef/public_html/wp-content/plugins/domainer/uninstall.php(51): Domainer\uninstall()
#1 /home/abcdef/public_html/wp-admin/includes/plugin.php(1259): include_once('/home/abcdef/...')
#2 /home/abcdef/public_html/wp-admin/includes/plugin.php(965): uninstall_plugin('domainer/domain...')
#3 /home/abcdef/public_html/wp-admin/includes/ajax-actions.php(4572): delete_plugins(Array)
#4 /home/abcdef/public_html/wp-includes/class-wp-hook.php(287): wp_ajax_delete_plugin('')
#5 /home/abcdef/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#6 /home/abcdef/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#7 /home/abcdef/public_html/wp-admin/admin-ajax.php(176): do_action('wp_ajax_de in /home/abcdef/public_html/wp-content/plugins/domainer/uninstall.php on line 35

**Comment by dougwollison** [comment]
Okay apparently my uninstall script is more broken than I realized. This error just means it's not able to remove it's options and database table, which you can do manually in phpMyAdmin if you feel like it (leaving them won't harm anything).

Based on that error it should be safe to delete the domainer plugin folder manually.

**Comment by cornishpasty** [comment]
Thanks, just did a backup and deleted manually, all fine. Phew!

Thanks for your prompt replies!

**Comment by dougwollison** [comment]
No problem, sorry for the trouble.
